name: 7-24 Yayin
on:
  workflow_dispatch:
jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Kurulum
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip
          sudo pip3 install yt-dlp
      - name: Baslat
        run: |
          while true; do
            URL=$(yt-dlp -g -f "best[ext=mp4]" "https://youtu.be/WBZUFiJU6N0?si=xHqdMada7hMy87QN")
            ffmpeg -re -i "$URL" -c copy -f flv "rtmp://a.rtmp.youtube.com/live2/54k8-jqcu-6mjk-905h-epxp"
          done









      
      



      
      
          
          


